# Generated by Django 5.1.1 on 2025-10-19 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('mood_preference', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('tired', 'Tired'), ('confused', 'Confused'), ('chill', 'Chill'), ('anxious', 'Anxious'), ('stressed', 'Stressed'), ('motivated', 'Motivated'), ('grateful', 'Grateful'), ('bored', 'Bored'), ('excited', 'Excited'), ('lonely', 'Lonely'), ('calm', 'Calm'), ('overwhelmed', 'Overwhelmed'), ('content', 'Content'), ('focused', 'Focused'), ('neutral', 'Neutral')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
